name: Respond to Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const commentBody = "Gracias por tu contribución! Revisaremos tu PR pronto.";
            
            await github.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: commentBody,
            });
