name: Create Comment

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create Comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number; // Asegúrate de que el issue existe en el contexto
            const comment = "¡Este es un comentario!";
            await github.issues.createComment({
              ...context.repo,
              issue_number,
              body: comment,
            });
