name: Simple Welcome Message

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on New Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const commentBody = "¡Gracias por abrir un issue! Lo revisaremos pronto.";

            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: issueNumber,
              body: commentBody,
            });
